// src/frontend/js/pages/Login.vue
<template>
  <div class="mx-auto my-2 p-3" style="max-width: 20rem">
    <form @submit.prevent="login" class="d-flex flex-column">
      <div class="login-logo my-5 d-flex justify-content-center" v-html="logo"></div>
      <label for="username" class="mb-2">{{ $t("username") }}</label>
      <input name="username" class="c-input" id="username" autocomplete="off" required autofocus />
      <label for="password" class="mb-2 mt-3">{{ $t("password") }}</label>
      <input name="password" class="c-input" id="password" type="password" required />
      <button class="c-button mt-3" type="submit">{{ $t("login") }}</button>
      <div class="fixed-top p-2 text-center bg-danger text-white" v-if="hasError">{{ $t("login_error") }}</div>
    </form>
  </div>
</template>

<script lang="ts">
import { Lang } from "../i18n";
import icons from "../icons";
import { defineComponent } from "vue";

export default defineComponent({
  props: {
    onLogin: { type: Function, required: true },
  },
  data() {
    return {
      logo: icons.anchor,
      hasError: false,
    };
  },
  created() {
    this.$t.set(document.documentElement.lang as Lang);
  },
  methods: {
    login(event: Event) {
      event.preventDefault();
      var data = new FormData(event.target as HTMLFormElement);
      fetch("./login", { method: "POST", body: data }).then(res => {
        if (res.ok) {
          this.onLogin();
        } else {
          this.hasError = true;
        }
      });
    },
  },
});
</script>

// src/frontend/js/pages/Login.tsx
import { useState } from "preact/hooks";
import { useI18n } from "../i18n";
import icons from "../icons";

interface LoginProps {
  onLogin: () => void;
}

export default function Login({ onLogin }: LoginProps) {
  const { t } = useI18n();
  const [hasError, setHasError] = useState(false);

  const handleSubmit = (event: Event) => {
    event.preventDefault();
    const data = new FormData(event.target as HTMLFormElement);
    fetch("./login", { method: "POST", body: data }).then(res => {
      if (res.ok) {
        onLogin();
      } else {
        setHasError(true);
      }
    });
  };

  return (
    <div className="mx-auto my-2 p-3" style={{ maxWidth: "20rem" }}>
      <form onSubmit={handleSubmit} className="d-flex flex-column">
        <div
          className="login-logo my-5 d-flex justify-content-center"
          dangerouslySetInnerHTML={{ __html: icons.anchor }}
        />
        <label htmlFor="username" className="mb-2">
          {t("username")}
        </label>
        <input
          name="username"
          className="c-input"
          id="username"
          autoComplete="off"
          required
          autoFocus
        />
        <label htmlFor="password" className="mb-2 mt-3">
          {t("password")}
        </label>
        <input name="password" className="c-input" id="password" type="password" required />
        <button className="c-button mt-3" type="submit">
          {t("login")}
        </button>
        {hasError && (
          <div className="fixed-top p-2 text-center bg-danger text-white">{t("login_error")}</div>
        )}
      </form>
    </div>
  );
}
