// src/frontend/js/components/drag.vue
<template>
<div class="drag"></div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  props: ["width"],
  mounted() {
    var self = this;
    let startX = 0;
    let initW = 0;
    var onMouseMove = function (e: MouseEvent) {
      var offset = e.clientX - startX;
      var newWidth = initW + offset;
      self.$emit("resize", newWidth);
    };
    var onMouseUp = function (e: MouseEvent) {
      document.removeEventListener("mousemove", onMouseMove);
      document.removeEventListener("mouseup", onMouseUp);
    };
    this.$el.addEventListener("mousedown", function (e: MouseEvent) {
      startX = e.clientX;
      initW = self.width;
      document.addEventListener("mousemove", onMouseMove);
      document.addEventListener("mouseup", onMouseUp);
    });
  },
});
</script>

// src/frontend/js/components/Drag.tsx
import { useCallback } from "preact/hooks";

interface DragProps {
  width: number;
  onResize: (width: number) => void;
}

export default function Drag({ width, onResize }: DragProps) {
  const onMouseDown = useCallback(
    (e: MouseEvent) => {
      const startX = e.clientX;
      const initW = width;

      const onMouseMove = (ev: MouseEvent) => {
        const offset = ev.clientX - startX;
        onResize(initW + offset);
      };

      const onMouseUp = () => {
        document.removeEventListener("mousemove", onMouseMove);
        document.removeEventListener("mouseup", onMouseUp);
      };

      document.addEventListener("mousemove", onMouseMove);
      document.addEventListener("mouseup", onMouseUp);
    },
    [width, onResize],
  );

  return <div className="drag" onMouseDown={onMouseDown} />;
}
