// src/frontend/js/components/Dropdown.tsx
import { useState, useRef, useEffect, useCallback } from "preact/hooks";
import type { ComponentChildren, Ref } from "preact";

export interface DropdownHandle {
  hide: () => void;
  show: () => void;
  toggle: () => void;
}

interface DropdownProps {
  button: ComponentChildren;
  toggleClass: string;
  drop: "right" | "center";
  title: string;
  disabled?: boolean;
  children: ComponentChildren;
  ref?: Ref<DropdownHandle>;
}

export default function Dropdown({
  button,
  toggleClass,
  drop,
  title,
  disabled,
  children,
  ref,
}: DropdownProps) {
  const [open, setOpen] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);
  const menuRef = useRef<HTMLDivElement>(null);

  const hide = useCallback(() => setOpen(false), []);
  const show = useCallback(() => setOpen(true), []);
  const toggle = useCallback(() => setOpen(prev => !prev), []);

  if (ref) {
    if (typeof ref === "function") {
      ref({ hide, show, toggle });
    } else {
      (ref as { current: DropdownHandle | null }).current = { hide, show, toggle };
    }
  }

  useEffect(() => {
    if (!open) return;

    const clickHandler = (e: MouseEvent) => {
      const target = e.target as HTMLElement;
      const menu = menuRef.current;
      if (!menu || !menu.contains(target)) {
        hide();
      } else if (target.closest(".c-dropdown-item") !== null) {
        hide();
      }
    };

    document.addEventListener("click", clickHandler);
    return () => document.removeEventListener("click", clickHandler);
  }, [open, hide]);

  const onButtonClick = (e: MouseEvent) => {
    e.stopPropagation();
    if (!disabled) toggle();
  };

  const menuCls = `c-dropdown position-absolute top-100 z-1 ${
    drop === "center" ? "start-50 translate-middle-x" : "end-0"
  }`;

  return (
    <div className="position-relative d-inline-flex flex-column" ref={containerRef}>
      <button
        type="button"
        className={`c-button-pill ${toggleClass}`}
        onClick={onButtonClick}
        title={title}
        disabled={disabled}>
        {button}
      </button>
      {open && (
        <div ref={menuRef} className={menuCls}>
          {children}
        </div>
      )}
    </div>
  );
}

// src/frontend/js/components/dropdown.vue
<template>
  <div class="position-relative d-inline-flex flex-column">
    <button class="c-button-pill" :class="toggleClass" @click="toggle">
      <slot name="button"></slot>
    </button>
    <div
      ref="dropdown"
      class="c-dropdown position-absolute top-100 z-1"
      :class="{
        'start-50 translate-middle-x': $props.drop === 'center',
        'end-0': $props.drop === 'right',
      }"
      v-if="open">
      <slot></slot>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  inheritAttrs: false,
  props: {
    toggleClass: {
      type: String,
      required: true,
    },
    drop: {
      type: String,
      required: true,
      validator: (value: string) => ["right", "center"].includes(value),
    },
    title: {
      type: String,
      required: true,
    },
  },
  data() {
    return { open: false };
  },
  methods: {
    toggle(event: Event) {
      event.stopPropagation()
      this.open ? this.hide() : this.show();
    },
    show() {
      this.open = true;
      document.addEventListener("click", this.clickHandler);
    },
    hide() {
      this.open = false;
      document.removeEventListener("click", this.clickHandler);
    },
    clickHandler(e: MouseEvent) {
      const dropdown = this.$refs.dropdown as HTMLElement;
      const target = e.target as HTMLElement;
      // Did click happen outside this component's DOM element?
      if (dropdown === null || !dropdown.contains(target)) this.hide();
      // Is the target (or its parent) a clickable option (e.g., button or link)?
      if (target.closest(".c-dropdown-item") !== null) this.hide();
    },
  },
});
</script>
