// src/frontend/js/components/Modal.tsx
import { useEffect, useRef } from "preact/hooks";
import type { ComponentChildren } from "preact";

interface ModalProps {
  open: boolean;
  onHide: () => void;
  children: ComponentChildren;
}

export default function Modal({ open, onHide, children }: ModalProps) {
  const dialogRef = useRef<HTMLDialogElement>(null);

  useEffect(() => {
    const el = dialogRef.current;
    if (!el) return;
    if (open) {
      if (!el.open) el.showModal();
    } else {
      if (el.open) el.close();
    }
  }, [open]);

  const onBackdropClick = (e: MouseEvent) => {
    if (e.target === dialogRef.current) {
      onHide();
    }
  };

  return (
    <dialog className="c-dialog" ref={dialogRef} onClose={onHide} onClick={onBackdropClick}>
      {children}
    </dialog>
  );
}

// src/frontend/js/components/modal.vue
<template>
  <dialog class="c-dialog" ref="dialog" @close="$emit('hide')" @click="onBackdropClick">
    <slot></slot>
  </dialog>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  props: ["open"],
  emits: ["hide"],
  watch: {
    open(open) {
      const el = this.$refs.dialog as HTMLDialogElement;
      if (open) el.showModal();
      else el.close();
    },
  },
  methods: {
    onBackdropClick(e: MouseEvent) {
      if (e.target === this.$refs.dialog) {
        this.$emit("hide");
      }
    },
  },
});
</script>
