// src/frontend/js/components/toast.vue
<template>
  <TransitionGroup
    tag="div"
    class="position-fixed bottom-0 end-0 pb-3 pe-3 d-flex flex-column align-items-end gap-2 z-4 pe-none"
    name="toast">
    <div
      class="c-toast d-flex align-items-start gap-2"
      v-for="t in list"
      :key="t.id"
      :class="{ 'text-bg-danger text-light': t.opts?.level === 'fail' }">
      <v-icon v-if="t.opts?.level === 'fail'" name="alert-circle" />
      <div class="flex-grow-1">
        <div>{{ t.message.title }}</div>
        <div class="opacity-50" v-if="t.message.description">
          {{ t.message.description }}
        </div>
      </div>
      <button class="c-button-link" @click="remove(t.id)" v-if="t.opts?.closeable === true">
        <v-icon name="x" />
      </button>
    </div>
  </TransitionGroup>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import icon from "./icon.vue";

type Level = "info" | "fail";
type Options = { level?: Level; closeable?: boolean; err?: unknown };
type Toast = { id: string; message: Message; opts?: Options };
type Message = { title: string; description?: string };

const getUUID = () =>
  crypto?.randomUUID?.() ?? Date.now().toString(36) + Math.random().toString(36).slice(2);

export default defineComponent({
  components: { "v-icon": icon },
  data() {
    return { list: [] as Toast[] };
  },
  methods: {
    addToast(message: Message, opts?: Options) {
      var t: Toast = { id: getUUID(), message, opts: opts };
      this.list.push(t);
      setTimeout(() => this.remove(t.id), 3000);
    },
    remove(id: string) {
      this.list = this.list.filter(x => x.id !== id);
    },
  },
});
</script>

// src/frontend/js/components/Toast.tsx
import { useState, useEffect } from "preact/hooks";
import Icon from "./Icon";

export type ToastLevel = "info" | "fail";

export interface ToastOptions {
  level?: ToastLevel;
  closeable?: boolean;
  err?: unknown;
}

export interface ToastMessage {
  title: string;
  description?: string;
}

export interface ToastItem {
  id: string;
  message: ToastMessage;
  opts?: ToastOptions;
}

const getUUID = () =>
  crypto?.randomUUID?.() ?? Date.now().toString(36) + Math.random().toString(36).slice(2);

type Listener = (toasts: ToastItem[]) => void;
let toasts: ToastItem[] = [];
const listeners = new Set<Listener>();

function notify() {
  listeners.forEach(l => l([...toasts]));
}

export function showToast(message: ToastMessage, opts?: ToastOptions) {
  const item: ToastItem = { id: getUUID(), message, opts };
  toasts = [...toasts, item];
  notify();
  setTimeout(() => removeToast(item.id), 3000);
}

export function removeToast(id: string) {
  toasts = toasts.filter(t => t.id !== id);
  notify();
}

export default function ToastContainer() {
  const [list, setList] = useState<ToastItem[]>(toasts);

  useEffect(() => {
    listeners.add(setList);
    return () => {
      listeners.delete(setList);
    };
  }, []);

  return (
    <div className="position-fixed bottom-0 end-0 pb-3 pe-3 d-flex flex-column align-items-end gap-2 z-4 pe-none">
      {list.map(t => (
        <div
          key={t.id}
          className={`c-toast d-flex align-items-start gap-2 ${
            t.opts?.level === "fail" ? "text-bg-danger text-light" : ""
          }`}>
          {t.opts?.level === "fail" && <Icon name="alert-circle" />}
          <div className="flex-grow-1">
            <div>{t.message.title}</div>
            {t.message.description && <div className="opacity-50">{t.message.description}</div>}
          </div>
          {t.opts?.closeable === true && (
            <button type="button" className="c-button-link" onClick={() => removeToast(t.id)}>
              <Icon name="x" />
            </button>
          )}
        </div>
      ))}
    </div>
  );
}
