// src/frontend/js/components/RelativeTime.tsx
import { useState, useEffect } from "preact/hooks";
import { dateRepr, dateTimeString, relRepaintDelay } from "../utils";

interface RelativeTimeProps {
  val: string;
  locale: string;
}

export default function RelativeTime({ val, locale }: RelativeTimeProps) {
  const [formatted, setFormatted] = useState("");
  const date = new Date(val);
  const title = dateTimeString(date, locale);

  useEffect(() => {
    let timer: number | undefined;

    function repaint() {
      setFormatted(dateRepr(date, locale));
      const delay = relRepaintDelay(date);
      if (delay !== null) {
        timer = window.setTimeout(repaint, delay);
      }
    }

    repaint();

    return () => {
      if (timer !== undefined) window.clearTimeout(timer);
    };
  }, [val, locale]);

  return (
    <time dateTime={val} title={title}>
      {formatted}
    </time>
  );
}

// src/frontendold/js/components/relative-time.vue
<template>
  <time :datetime="val" :title="title">{{ formatted }}</time>
</template>

<script lang="ts">
import { dateRepr, dateTimeString, relRepaintDelay } from "../utils";
import { defineComponent } from "vue";

export default defineComponent({
  props: ["val", "locale"],
  data() {
    return {
      date: new Date(this.val),
      formatted: "" as string,
      timer: undefined as number | undefined,
    };
  },
  computed: {
    title(): string {
      return dateTimeString(this.date, this.locale);
    },
  },
  created() {
    this.repaint();
  },
  unmounted() {
    window.clearTimeout(this.timer);
  },
  methods: {
    repaint() {
      this.formatted = dateRepr(this.date, this.locale);
      window.clearTimeout(this.timer);
      const delay = relRepaintDelay(this.date);
      if (delay !== null) {
        this.timer = window.setTimeout(() => this.repaint(), delay);
      }
    },
  },
  watch: {
    locale() {
      this.repaint();
    },
  },
});
</script>
